version: '3.2'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 2565:2565
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db/expenses-db?sslmode=disable
      PORT: :2565
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: postgres:12.12
    user: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expenses-db
    volumes:
      - ./expense.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
